spring:
   application:
      name: tourism-app
   datasource:
      url: jdbc:mysql://localhost:3306/P1TORKA?useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect    
server:
  port: 8081
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true 
      