spring:
   application:
      name: tourism-app
   datasource:
      tourism:
         url:jdbc:mysql://localhost:3306/P1TORKA?useSSL=false&createDatabaseIfNotExist=false
         username:root
         password:root
         driverClassName:com.mysql.jdbc.Driver
   jpa:
      hibernate:
         ddl-auto: update
   hikari:
      connectionTimeout:30000
      idleTimeout:600000
      maxLifetime:1800000  		
server:
  port: 8081
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true 
      